name: 'Maya - Books, Apps and more....'
favicon: null
layout_spectrum: 0.75032
typography_spectrum: 0.2872719143051654
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#010101'
    - '#ed5974'
    - '#af95c3'
    - '#464f56'
  brandStrength: 0.1875
  lightness: 0.5504745242651552
  saturation: 0.5625
  rhythmicContrast: 0.6015890340786427
purpose: []
