layout_spectrum: 0.0896767433732748
typography_spectrum: 0.9782039320562035
color:
  brandColors:
    - '#FF6138'
    - '#FFFF9D'
    - '#BEEB9F'
    - '#79BD8F'
    - '#00A388'
  brandStrength: 0.8839454213157296
  lightness: 0.7370685113128275
  saturation: 0.4448453129734844
  rhythmicContrast: 0.6585599852260202
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
name: 'Maya - Stories, Apps and more....'
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Maya's published Books
    url: 'https://www.amazon.com/Rich-Okun/e/B00DZO54IG/'
    type: external
  - name: Maya bedtime story 1
    url: 'http://www.the-office.com/bedtime-story/maya.htm'
    type: external
  - name: Maya bedtime story 2
    url: 'http://www.the-office.com/bedtime-story/maya2.htm'
    type: external
  - name: Maya bedtime story 3
    url: 'http://www.the-office.com/bedtime-story/maya3.htm'
    type: external
  - name: Maya's Daily Meds - app
    id: d5159079-b769-4d45-b895-779fab7ec5eb
    type: content
  - name: app Splashscreens
    id: 3d439992-9d3b-4022-ac57-ac2a7db1f490
    type: content
  - name: Maya Posts
    url: 'https://thegrid.ai/maya/'
    type: external
favicon: null
purpose: []
