typography_spectrum: 0.2872719143051654
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#d5c4b7'
    - '#736960'
    - '#4cdefd'
  brandStrength: 0.1875
  lightness: 0.5504745242651552
  saturation: 0.4375
  rhythmicContrast: 0.6015890340786427
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.75032
analytics:
  google: null
  facebook: null
  twitter: null
name: 'Maya - Stories, Apps and more....'
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: App Splashscreens
    id: 3d439992-9d3b-4022-ac57-ac2a7db1f490
    type: content
  - name: Maya's Daily Meds
    id: d5159079-b769-4d45-b895-779fab7ec5eb
    type: content
  - name: 'MAYA, by Rich Okun, at BEDTIME-STORY.COM'
    id: 4f7e1949-14b2-484e-abdc-9db253d8b6c4
    type: content
  - name: Maya Bedtime-Story 2
    id: 84c2f03f-b33c-42ac-9d8c-20477b050f36
    type: content
  - name: 'Maya, Book 3, The Hike Bedtime-Story 3'
    id: a93922bb-d34c-476f-9ee4-48d097dc249b
    type: content
favicon: null
purpose: []
