typography_spectrum: 0.2872719143051654
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#d5c4b7'
    - '#736960'
    - '#4cdefd'
  brandStrength: 0.1875
  lightness: 0.5504745242651552
  saturation: 0.4375
  rhythmicContrast: 0.6015890340786427
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.75032
analytics:
  google: null
  facebook: null
  twitter: null
name: 'Maya - Books, Apps and more....'
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Maya posts
    id: 6af57fef-b2e4-48a2-b54d-2b8ff7a7c21b
    type: content
favicon: null
purpose: []
