typography_spectrum: 0.2872719143051654
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#d5c4b7'
    - '#736960'
    - '#4cdefd'
  brandStrength: 0.1875
  lightness: 0.5504745242651552
  saturation: 0.4375
  rhythmicContrast: 0.6015890340786427
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.75032
analytics:
  google: null
  facebook: null
  twitter: null
name: 'Maya - Stories, Apps and more....'
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Maya Posts
    url: 'https://thegrid.ai/maya/'
    type: external
  - name: Maya bedtime story 1
    url: 'http://www.the-office.com/bedtime-story/maya.htm'
    type: external
  - name: Maya bedtime story 2
    url: 'http://www.the-office.com/bedtime-story/maya2.htm'
    type: external
  - name: Maya bedtime story 3
    url: 'http://www.the-office.com/bedtime-story/maya3.htm'
    type: external
  - name: app Splashscreens
    id: 3d439992-9d3b-4022-ac57-ac2a7db1f490
    type: content
  - name: Maya's Daily Meds - app
    id: d5159079-b769-4d45-b895-779fab7ec5eb
    type: content
favicon: null
purpose: []
