name: 'Maya - Books, Apps and more....'
favicon: null
layout_spectrum: 0.83502
typography_spectrum: 0.2872719143051654
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#060606'
    - '#fefefe'
    - '#fd99fc'
    - '#cf7f1c'
    - '#177a06'
  brandStrength: 0.1875
  lightness: 0.5504745242651552
  saturation: 0.660521640907973
  rhythmicContrast: 0.6015890340786427
purpose: []
