name: 'Maya - Books, Apps and more....'
favicon: null
layout_spectrum: 0.75032
typography_spectrum: 0.2872719143051654
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#d5c4b7'
    - '#736960'
    - '#4cdefd'
  brandStrength: 0.1875
  lightness: 0.5504745242651552
  saturation: 0.4375
  rhythmicContrast: 0.6015890340786427
purpose: []
