name: 'Maya - Books, Apps and more....'
favicon: null
layout_spectrum: 0.6637273004744202
typography_spectrum: 0.2872719143051654
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1d2337'
    - '#2995ec'
    - '#dbb47f'
    - '#ac7127'
  brandStrength: 0.32291121245361865
  lightness: 0.5504745242651552
  saturation: 0.660521640907973
  rhythmicContrast: 0.6015890340786427
purpose: []
